fails:Executing break from within a block returns from the invoking singleton method
fails:Executing break from within a block returns from the invoking method with the argument to break
fails:Executing break from within a block returns from the original invoking method even in case of chained calls
fails:Breaking out of a loop with a value stops a yielded method at the correct spot